### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [CKhalili/prj-rev-bwfs-dasmoto#3]
Alternatively, you could use `.item h2` as your selector to specify the following shared properties between the heading elements. This could help you avoid repetition in code:

```css
.item h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

https://github.com/CKhalili/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Art%20and%20Craft/resources/style.css#L8-L28
